[target.'cfg(target_os="macos")']
# Postgres symbols won't be available until runtime
rustflags = ["-Clink-arg=-Wl,-undefined,dynamic_lookup"]

[target.'cfg(target_os="linux")']
rustflags = ["-Ctarget-feature=+avx2,+fma"]
